{% set name = "xcb-util-image" %}
{% set version = "0.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://xcb.freedesktop.org/dist/{{ name }}-{{ version }}.tar.xz
  sha256: ccad8ee5dadb1271fd4727ad14d9bd77a64e505608766c4e98267d9aede40d3d

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('xcb-util-image', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - libxcb {{ libxcb }}
    - xcb-util {{ xcb_util }}
    - xorg-xorgproto {{ xorg_xorgproto }}

test:
  commands:
    - test -f ${PREFIX}/lib/libxcb-image.so

about:
  home: https://xcb.freedesktop.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxcb-util
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxcb-util
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Port of Xlib XImage and XShmImage functions
  description: |
    Port of Xlib XImage and XShmImage functions

extra:
  recipe-maintainers:
    - erykoff
